### ISSUE TITLE
Improve source code

### ISSUE THREAD

**Issue by Th0rgal** [nexmind-space/nexmind-node#1]
Do you prefer

- usage of global (one usage)
https://github.com/nexmind-space/nexmind-node/tree/15f85358f18654e9f7112f6f456ad77e19e83ed8

- more "object" oriented source code (no global)
https://github.com/nexmind-space/nexmind-node/tree/707ae8ec2263103ff503e49c170366c7d5892a9b

@Julien00859

**Comment by Julien00859** [comment]
second one is nice
